# Generated by Django 3.2.12 on 2022-02-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100)),
                ('image_url', models.URLField(max_length=250)),
                ('setup', models.CharField(max_length=250)),
                ('delivery', models.TextField()),
            ],
        ),
    ]
